### ISSUE TITLE
Annotation ground truth annotate.launch issue

### ISSUE THREAD

**Issue by hggm02** [angusleigh/leg_tracker_benchmarks#1]
the annotate.launch file does not work. There is a problem in this part:
params
  param name="readbag_filename" value="/home/angus/annotation_insepction/benchmark_1.bag" 

where the location of benchmark_1.bag is coded into the file. I tried changing it but this caused issues because there is no "benchmark_1.bag" anywhere. It would be very helpful if you can share that file. 
Thank you

**Comment by angusleigh** [comment]
Sorry for the tardy reply. I'm guessing you got it working since you just closed the issue? benchmark_1.bag doesn't actually exist - it's is just a placeholder you need to replace with the name of the rosbag you want to annotate.
