### ISSUE TITLE
PositionMeasurement.h is missing

### ISSUE THREAD

**Issue by nadalalee** [angusleigh/leg_tracker_benchmarks#3]
Hi,when I try to compile the leg_tracker_benchmarks,there is something wrong which shows that the PositionMeasurement.h : not such file or directory and there is also no such file in people_msgs directory.Is PositionMeasurement,h not released?

**Comment by angusleigh** [comment]
Fixed by ff947d1b9a3cb114940442aec0a021425a1f39e2
